### ISSUE TITLE
Test set overused, use hold out sets instead.

### ISSUE THREAD

**Issue by kiwidamien** [kiwidamien/github_training#6]
In pull request #5 (and earlier) we are modifying the model used and then making decisions directly on the test set. 

Instead, we should be looking at cross validated scores. The test set should be reserved for when we have picked the final model, to allow us to estimate how well it will apply to new data.

**Comment by cliffclive** [comment]
How would you go about evaluating cross val scores in Excel?

Slightly related question -- is the intention here to show how team member working in Excel and Jupyter would store their work in the same repo? I'm trying to understand the example use case.

**Comment by kiwidamien** [comment]
Good point! The Excel file was from the original analysis. We should eliminate it to avoid confusion for future development.

We will use the `cross_val_score` from sklearn, but only in the Python notebook.

**Comment by kiwidamien** [comment]
Should be fixed in PR #7
